<?php
/**
 * Status tab and recommended-settings renderers.
 *
 * Part of BEPLUSPB_Admin, split out of class-bepluspb-admin.php. A trait is used
 * (rather than a separate class) so every method keeps its exact `self::`/`static`
 * semantics, visibility and hook callbacks; behaviour is unchanged.
 *
 * @package Beplus_Performance_Booster
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

trait BEPLUSPB_Admin_Tabs_Status {

	/**
	 * Render the "Status" tab — live server-side system checks, read-only.
	 *
	 * Layout:
	 *  - Top: Recommendations panel (warnings + suggestions for fixes/improvements).
	 *  - Below: Six panels in a two-column CSS grid for raw environment data.
	 */
	private static function render_section_status() {

		// ---- Helpers -----------------------------------------------------------

		/**
		 * Convert a PHP ini size string (e.g. "128M", "1G") to bytes.
		 * Returns -1 when the value is unlimited ("-1").
		 */
		$parse_bytes = static function ( $val ) {
			$val = trim( (string) $val );
			if ( '-1' === $val ) {
				return -1;
			}
			$last = strtolower( substr( $val, -1 ) );
			$num  = (float) $val;
			switch ( $last ) {
				case 'g':
					$num *= 1024;
					// fall through.
				case 'm':
					$num *= 1024;
					// fall through.
				case 'k':
					$num *= 1024;
			}
			return (int) $num;
		};

		/**
		 * Return a coloured status badge span.
		 *
		 * @param string $type  ok | warn | error | info
		 * @param string $label Text to display inside the badge.
		 * @return string Safe HTML.
		 */
		$badge = static function ( $type, $label ) {
			return '<span class="bepluspb-status-badge bepluspb-status-' . esc_attr( $type ) . '">'
				. esc_html( $label )
				. '</span>';
		};

		/**
		 * Echo one status-table row.
		 *
		 * @param string $label      Left-side label.
		 * @param string $value      Right-side value text (will be esc_html'd).
		 * @param string $badge_html Optional badge HTML (already escaped — echoed raw).
		 */
		$row = static function ( $label, $value, $badge_html = '' ) {
			echo '<div class="bepluspb-status-row">';
			echo '<span class="bepluspb-status-label">' . esc_html( $label ) . '</span>';
			echo '<span class="bepluspb-status-value">' . esc_html( $value );
			if ( $badge_html ) {
				echo ' ' . $badge_html; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- generated by $badge() which escapes internally.
			}
			echo '</span>';
			echo '</div>';
		};

		// Common translated strings reused across all status panels.
		$t_yes      = __( 'Yes', 'beplus-performance-booster' );
		$t_no       = __( 'No', 'beplus-performance-booster' );
		$t_on       = __( 'On', 'beplus-performance-booster' );
		$t_off      = __( 'Off', 'beplus-performance-booster' );
		$t_ok       = __( 'OK', 'beplus-performance-booster' );
		$t_warning  = __( 'Warning', 'beplus-performance-booster' );
		$t_error    = __( 'Error', 'beplus-performance-booster' );
		$t_info     = __( 'Info', 'beplus-performance-booster' );
		$t_unl      = __( 'Unlimited', 'beplus-performance-booster' );
		$t_low      = __( 'Low', 'beplus-performance-booster' );
		$t_missing  = __( 'Missing', 'beplus-performance-booster' );
		$t_enabled  = __( 'Enabled', 'beplus-performance-booster' );
		$t_disabled = __( 'Disabled', 'beplus-performance-booster' );

		// =========================================================================
		// Gather all data up-front so we can render both check rows and the
		// recommendations panel from a single source of truth.
		// =========================================================================

		// ---- PHP ----
		$php_ver    = phpversion();
		$mem        = ini_get( 'memory_limit' );
		$max_ex     = ini_get( 'max_execution_time' );
		$post_max   = ini_get( 'post_max_size' );
		$upload_max = ini_get( 'upload_max_filesize' );
		$has_zlib   = extension_loaded( 'zlib' );
		$has_mb     = extension_loaded( 'mbstring' );

		// ---- PHP Extensions for Object Cache / performance ----
		$ext_checks = array(
			'redis'     => array(
				'label'    => 'Redis',
				'loaded'   => extension_loaded( 'redis' ),
				'required' => false,
				'note'     => __( 'Required for Redis object cache.', 'beplus-performance-booster' ),
			),
			'memcached' => array(
				'label'    => 'Memcached',
				'loaded'   => extension_loaded( 'memcached' ),
				'required' => false,
				'note'     => __( 'Required for Memcached object cache.', 'beplus-performance-booster' ),
			),
			'opcache'   => array(
				'label'    => 'OPcache',
				'loaded'   => extension_loaded( 'Zend OPcache' ),
				'required' => false,
				'note'     => __( 'PHP bytecode cache — strongly recommended for performance.', 'beplus-performance-booster' ),
			),
			'curl'      => array(
				'label'    => 'cURL',
				'loaded'   => extension_loaded( 'curl' ),
				'required' => true,
				'note'     => __( 'Required for HTTP requests (WordPress core dependency).', 'beplus-performance-booster' ),
			),
			'gd'        => array(
				'label'    => 'GD / ImageMagick',
				'loaded'   => extension_loaded( 'gd' ) || extension_loaded( 'imagick' ),
				'required' => false,
				'note'     => __( 'Required for image processing (thumbnails, WebP).', 'beplus-performance-booster' ),
			),
			'mbstring'  => array(
				'label'    => 'mbstring',
				'loaded'   => extension_loaded( 'mbstring' ),
				'required' => true,
				'note'     => __( 'Multi-byte string functions — required by WordPress core.', 'beplus-performance-booster' ),
			),
			'openssl'   => array(
				'label'    => 'OpenSSL',
				'loaded'   => extension_loaded( 'openssl' ),
				'required' => false,
				'note'     => __( 'Required for HTTPS / encrypted connections.', 'beplus-performance-booster' ),
			),
			'zlib'      => array(
				'label'    => 'zlib',
				'loaded'   => extension_loaded( 'zlib' ),
				'required' => false,
				'note'     => __( 'Used for gzip output compression.', 'beplus-performance-booster' ),
			),
			'intl'      => array(
				'label'    => 'intl',
				'loaded'   => extension_loaded( 'intl' ),
				'required' => false,
				'note'     => __( 'Internationalisation support.', 'beplus-performance-booster' ),
			),
		);

		$mem_bytes = $parse_bytes( $mem );

		if ( version_compare( $php_ver, '7.4', '>=' ) ) {
			$php_ver_badge = $badge( 'ok', $t_ok );
		} elseif ( version_compare( $php_ver, '7.0', '>=' ) ) {
			$php_ver_badge = $badge( 'warn', $t_warning );
		} else {
			$php_ver_badge = $badge( 'error', $t_error );
		}

		if ( -1 === $mem_bytes ) {
			$mem_badge = $badge( 'ok', $t_unl );
		} elseif ( $mem_bytes >= 128 * 1024 * 1024 ) {
			$mem_badge = $badge( 'ok', $t_ok );
		} elseif ( $mem_bytes >= 64 * 1024 * 1024 ) {
			$mem_badge = $badge( 'warn', $t_warning );
		} else {
			$mem_badge = $badge( 'error', $t_low );
		}

		$max_ex_val   = (int) $max_ex;
		$max_ex_badge = ( 0 === $max_ex_val || $max_ex_val >= 30 )
			? $badge( 'ok', $t_ok )
			: $badge( 'warn', $t_warning );

		// ---- WordPress ----
		$wp_ver     = get_bloginfo( 'version' );
		$theme      = wp_get_theme();
		$theme_name = $theme->get( 'Name' ) . ' v' . $theme->get( 'Version' );
		$parent     = $theme->parent();
		$is_multi   = is_multisite();
		$wp_debug   = defined( 'WP_DEBUG' ) && WP_DEBUG;
		$sc_debug   = defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG;
		$wp_mem     = defined( 'WP_MEMORY_LIMIT' ) ? WP_MEMORY_LIMIT : '64M';
		$wp_max_mem = defined( 'WP_MAX_MEMORY_LIMIT' ) ? WP_MAX_MEMORY_LIMIT : '256M';
		$cron_dis   = defined( 'DISABLE_WP_CRON' ) && DISABLE_WP_CRON;

		$wp_mem_bytes = $parse_bytes( $wp_mem );
		$wp_mem_badge = ( -1 === $wp_mem_bytes || $wp_mem_bytes >= 128 * 1024 * 1024 )
			? $badge( 'ok', $t_ok )
			: $badge( 'warn', $t_low );

		// ---- Cache directory ----
		$cache_dir    = BEPLUSPB_CACHE_DIR;
		$dir_exists   = is_dir( $cache_dir );
		$dir_writable = $dir_exists ? wp_is_writable( $cache_dir ) : wp_is_writable( dirname( $cache_dir ) );
		$ht_path      = get_home_path() . '.htaccess';
		$ht_exists    = file_exists( $ht_path );
		$ht_writable  = $ht_exists ? wp_is_writable( $ht_path ) : wp_is_writable( dirname( $ht_path ) );
		$wc_writable  = wp_is_writable( WP_CONTENT_DIR );
		$cache_stats  = BEPLUSPB_Minify::get_cache_stats();
		$cache_size   = $cache_stats['size'] > 0 ? BEPLUSPB_Minify::human_filesize( $cache_stats['size'] ) : '0 B';
		$cache_count  = (int) $cache_stats['count'];

		// ---- Active plugins ----
		if ( ! function_exists( 'get_plugins' ) ) {
			require_once ABSPATH . 'wp-admin/includes/plugin.php';
		}
		$all_plugins    = get_plugins();
		$active_slugs   = get_option( 'active_plugins', array() );
		$active_plugins = array();
		foreach ( $active_slugs as $slug ) {
			if ( isset( $all_plugins[ $slug ] ) ) {
				$active_plugins[ $slug ] = $all_plugins[ $slug ];
			}
		}

		// Known potential conflicts keyed by plugin file (folder/file.php).
		$known_conflicts = array(
			// Caching plugins.
			'w3-total-cache/w3-total-cache.php'          => array(
				'type' => 'warn',
				'note' => __( 'May conflict — caching', 'beplus-performance-booster' ),
			),
			'wp-super-cache/wp-cache.php'                => array(
				'type' => 'warn',
				'note' => __( 'May conflict — caching', 'beplus-performance-booster' ),
			),
			'wp-rocket/wp-rocket.php'                    => array(
				'type' => 'warn',
				'note' => __( 'May conflict — caching and minification', 'beplus-performance-booster' ),
			),
			'litespeed-cache/litespeed-cache.php'        => array(
				'type' => 'warn',
				'note' => __( 'May conflict — caching', 'beplus-performance-booster' ),
			),
			'autoptimize/autoptimize.php'                => array(
				'type' => 'warn',
				'note' => __( 'May conflict — minification', 'beplus-performance-booster' ),
			),
			'hummingbird-performance/wp-hummingbird.php' => array(
				'type' => 'warn',
				'note' => __( 'May conflict — caching', 'beplus-performance-booster' ),
			),
			// Minification plugins.
			'fast-velocity-minify/fvm.php'               => array(
				'type' => 'warn',
				'note' => __( 'May conflict — minification', 'beplus-performance-booster' ),
			),
			'asset-cleanup/asset-cleanup.php'            => array(
				'type' => 'warn',
				'note' => __( 'May conflict — asset management', 'beplus-performance-booster' ),
			),
			// Page builders.
			'elementor/elementor.php'                    => array(
				'type' => 'info',
				'note' => __( 'Test output buffering with this plugin', 'beplus-performance-booster' ),
			),
			'divi-builder/divi-builder.php'              => array(
				'type' => 'info',
				'note' => __( 'Test output buffering with this plugin', 'beplus-performance-booster' ),
			),
			'bb-plugin/fl-builder.php'                   => array(
				'type' => 'info',
				'note' => __( 'Test output buffering with this plugin', 'beplus-performance-booster' ),
			),
			'beaver-builder-lite-version/fl-builder.php' => array(
				'type' => 'info',
				'note' => __( 'Test output buffering with this plugin', 'beplus-performance-booster' ),
			),
		);

		$flagged_plugins = array();
		$other_plugins   = array();
		foreach ( $active_plugins as $slug => $data ) {
			if ( isset( $known_conflicts[ $slug ] ) ) {
				$flagged_plugins[ $slug ] = array_merge( $data, $known_conflicts[ $slug ] );
			} else {
				$other_plugins[ $slug ] = $data;
			}
		}

		// ---- Server environment ----
		// phpcs:disable WordPress.Security.ValidatedSanitizedInput.InputNotSanitized
		$server_soft = isset( $_SERVER['SERVER_SOFTWARE'] ) ? sanitize_text_field( wp_unslash( $_SERVER['SERVER_SOFTWARE'] ) ) : 'N/A';
		$doc_root    = isset( $_SERVER['DOCUMENT_ROOT'] ) ? sanitize_text_field( wp_unslash( $_SERVER['DOCUMENT_ROOT'] ) ) : 'N/A';
		// phpcs:enable
		$server_os      = PHP_OS;
		$max_input_vars = ini_get( 'max_input_vars' );
		$has_curl       = function_exists( 'curl_version' );
		$openssl_ver    = defined( 'OPENSSL_VERSION_TEXT' ) ? OPENSSL_VERSION_TEXT : 'N/A';

		// ---- Plugin info ----
		$opts      = bepluspb_get_options();
		$cache_url = BEPLUSPB_Minify::cache_url();

		// =========================================================================
		// Output HTML
		// =========================================================================

		// Shorthand for On/Off badge.
		$on_off = static function ( $val ) use ( $badge, $t_on, $t_off ) {
			return $badge( $val ? 'ok' : 'error', $val ? $t_on : $t_off );
		};
		?>

		<div class="bepluspb-status-tab-header">
			<h2><?php esc_html_e( 'System Status', 'beplus-performance-booster' ); ?></h2>
		</div>

		<?php
		// ---- Recommendations panel (warnings + suggestions) ----------------------
		self::render_status_recommendations( $opts, $dir_writable, $dir_exists, $ht_writable, $ht_exists, $wc_writable, $php_ver, $wp_ver, $wp_debug, $is_multi, $has_zlib, $mem_bytes, $flagged_plugins );
		?>

		<div class="bepluspb-status-grid">

			<?php // ---- Panel 1: PHP Environment -------------------------------- ?>
			<div class="bepluspb-card">
				<div class="bepluspb-card-header">
					<h2><?php esc_html_e( 'PHP Environment', 'beplus-performance-booster' ); ?></h2>
				</div>
				<div class="bepluspb-card-body bepluspb-status-table">
					<?php
					$row( __( 'PHP Version', 'beplus-performance-booster' ), $php_ver, $php_ver_badge );
					$row( __( 'Memory Limit', 'beplus-performance-booster' ), $mem, $mem_badge );
					$row( __( 'Max Execution Time', 'beplus-performance-booster' ), $max_ex . 's', $max_ex_badge );
					$row( __( 'Post Max Size', 'beplus-performance-booster' ), $post_max );
					$row( __( 'Upload Max Filesize', 'beplus-performance-booster' ), $upload_max );
					$row( __( 'Zlib (gzip)', 'beplus-performance-booster' ), $has_zlib ? $t_enabled : $t_disabled, $badge( $has_zlib ? 'ok' : 'warn', $has_zlib ? $t_ok : $t_missing ) );
					$row( __( 'Mbstring', 'beplus-performance-booster' ), $has_mb ? $t_enabled : $t_disabled, $badge( $has_mb ? 'ok' : 'warn', $has_mb ? $t_ok : $t_missing ) );
					?>
				</div>
			</div>

			<?php // ---- Panel 2: WordPress Environment -------------------------- ?>
			<div class="bepluspb-card">
				<div class="bepluspb-card-header">
					<h2><?php esc_html_e( 'WordPress Environment', 'beplus-performance-booster' ); ?></h2>
				</div>
				<div class="bepluspb-card-body bepluspb-status-table">
					<?php
					$row( __( 'WordPress Version', 'beplus-performance-booster' ), $wp_ver, $badge( 'info', $t_info ) );
					$row( __( 'Active Theme', 'beplus-performance-booster' ), $theme_name );
					if ( $parent ) {
						$row( __( 'Parent Theme', 'beplus-performance-booster' ), $parent->get( 'Name' ) . ' v' . $parent->get( 'Version' ) );
					}
					$row( __( 'Multisite', 'beplus-performance-booster' ), $is_multi ? __( 'Yes (not recommended)', 'beplus-performance-booster' ) : $t_no, $badge( $is_multi ? 'warn' : 'ok', $is_multi ? $t_warning : $t_ok ) );
					$row( __( 'WP_DEBUG', 'beplus-performance-booster' ), $wp_debug ? __( 'On (development)', 'beplus-performance-booster' ) : __( 'Off (production)', 'beplus-performance-booster' ), $badge( $wp_debug ? 'warn' : 'ok', $wp_debug ? $t_warning : $t_ok ) );
					$row( __( 'SCRIPT_DEBUG', 'beplus-performance-booster' ), $sc_debug ? $t_on : $t_off, $badge( $sc_debug ? 'warn' : 'ok', $sc_debug ? $t_warning : $t_ok ) );
					$row( __( 'WP Memory Limit', 'beplus-performance-booster' ), $wp_mem, $wp_mem_badge );
					$row( __( 'WP Max Memory Limit', 'beplus-performance-booster' ), $wp_max_mem );
					$row( __( 'WP Cron', 'beplus-performance-booster' ), $cron_dis ? __( 'Disabled (external cron)', 'beplus-performance-booster' ) : $t_enabled, $badge( 'info', $t_info ) );
					?>
				</div>
			</div>

			<?php // ---- Panel 3: Cache Directory -------------------------------- ?>
			<div class="bepluspb-card">
				<div class="bepluspb-card-header">
					<h2><?php esc_html_e( 'Cache Directory & Permissions', 'beplus-performance-booster' ); ?></h2>
				</div>
				<div class="bepluspb-card-body bepluspb-status-table">
					<?php
					$row( __( 'Cache Directory', 'beplus-performance-booster' ), $cache_dir );
					$row( __( 'Directory Exists', 'beplus-performance-booster' ), $dir_exists ? $t_yes : __( 'No — will be created on first use', 'beplus-performance-booster' ), $badge( $dir_exists ? 'ok' : 'warn', $dir_exists ? $t_ok : $t_warning ) );
					$row( __( 'Directory Writable', 'beplus-performance-booster' ), $dir_writable ? $t_yes : $t_no, $badge( $dir_writable ? 'ok' : 'error', $dir_writable ? $t_ok : $t_error ) );
					$row( __( '.htaccess Path', 'beplus-performance-booster' ), $ht_path );
					$row( __( '.htaccess Exists', 'beplus-performance-booster' ), $ht_exists ? $t_yes : $t_no, $badge( $ht_exists ? 'ok' : 'warn', $ht_exists ? $t_ok : $t_warning ) );
					$row( __( '.htaccess Writable', 'beplus-performance-booster' ), $ht_writable ? $t_yes : $t_no, $badge( $ht_writable ? 'ok' : 'error', $ht_writable ? $t_ok : $t_error ) );
					$row( __( 'wp-content Writable', 'beplus-performance-booster' ), $wc_writable ? $t_yes : $t_no, $badge( $wc_writable ? 'ok' : 'error', $wc_writable ? $t_ok : $t_error ) );
					$row( __( 'Cached Files', 'beplus-performance-booster' ), (string) $cache_count );
					$row( __( 'Cache Size', 'beplus-performance-booster' ), $cache_size );
					?>
				</div>
			</div>

			<?php // ---- Panel 4: Active Plugins --------------------------------- ?>
			<div class="bepluspb-card">
				<div class="bepluspb-card-header">
					<h2><?php esc_html_e( 'Active Plugins', 'beplus-performance-booster' ); ?></h2>
				</div>
				<div class="bepluspb-card-body">
					<?php if ( empty( $active_plugins ) ) : ?>
						<p class="description"><?php esc_html_e( 'No active plugins found.', 'beplus-performance-booster' ); ?></p>
					<?php else : ?>

						<?php if ( ! empty( $flagged_plugins ) ) : ?>
						<div class="bepluspb-plugins-flagged">
							<?php
							foreach ( $flagged_plugins as $slug => $data ) :
								$c_type = $data['type'];
								$c_icon = 'warn' === $c_type ? '⚠️' : 'ℹ️';
								?>
							<div class="bepluspb-plugin-row bepluspb-plugin-row--flagged">
								<span class="bepluspb-plugin-info">
									<strong><?php echo esc_html( $data['Name'] ); ?></strong>
									<span class="bepluspb-plugin-ver">v<?php echo esc_html( $data['Version'] ); ?></span>
								</span>
								<span class="bepluspb-status-badge bepluspb-status-<?php echo esc_attr( $c_type ); ?>">
									<?php echo esc_html( $c_icon . ' ' . $data['note'] ); ?>
								</span>
							</div>
							<?php endforeach; ?>
						</div>
						<?php endif; ?>

						<?php if ( ! empty( $other_plugins ) ) : ?>
						<details class="bepluspb-all-plugins">
							<summary>
								<?php
								/* translators: %d: number of non-flagged active plugins. */
								printf( esc_html__( 'Show all %d plugins', 'beplus-performance-booster' ), count( $other_plugins ) );
								?>
							</summary>
							<div class="bepluspb-plugins-all">
								<?php foreach ( $other_plugins as $slug => $data ) : ?>
								<div class="bepluspb-plugin-row">
									<span class="bepluspb-plugin-info">
										<strong><?php echo esc_html( $data['Name'] ); ?></strong>
										<span class="bepluspb-plugin-ver">v<?php echo esc_html( $data['Version'] ); ?></span>
									</span>
								</div>
								<?php endforeach; ?>
							</div>
						</details>
						<?php endif; ?>

					<?php endif; ?>
				</div>
			</div>

			<?php // ---- Panel 5: Server Environment ----------------------------- ?>
			<div class="bepluspb-card">
				<div class="bepluspb-card-header">
					<h2><?php esc_html_e( 'Server Environment', 'beplus-performance-booster' ); ?></h2>
				</div>
				<div class="bepluspb-card-body bepluspb-status-table">
					<?php
					$row( __( 'Server Software', 'beplus-performance-booster' ), $server_soft );
					$row( __( 'Server OS', 'beplus-performance-booster' ), $server_os );
					$row( __( 'Document Root', 'beplus-performance-booster' ), $doc_root );
					$row( __( 'HTTPS', 'beplus-performance-booster' ), is_ssl() ? $t_yes : $t_no, $badge( is_ssl() ? 'ok' : 'warn', is_ssl() ? $t_ok : $t_warning ) );
					$row( __( 'Home URL', 'beplus-performance-booster' ), home_url() );
					$row( __( 'Site URL', 'beplus-performance-booster' ), site_url() );
					$row( __( 'WordPress Root', 'beplus-performance-booster' ), ABSPATH );
					$row( __( 'wp-content Directory', 'beplus-performance-booster' ), WP_CONTENT_DIR );
					$row( __( 'Max Input Vars', 'beplus-performance-booster' ), (string) $max_input_vars );
					$row( __( 'cURL', 'beplus-performance-booster' ), $has_curl ? $t_enabled : $t_disabled, $badge( $has_curl ? 'ok' : 'warn', $has_curl ? $t_ok : $t_missing ) );
					$row( __( 'OpenSSL', 'beplus-performance-booster' ), $openssl_ver );
					?>
				</div>
			</div>

			<?php // ---- Panel 6: Beplus Performance Booster Settings --------------------- ?>
			<div class="bepluspb-card">
				<div class="bepluspb-card-header">
					<h2><?php esc_html_e( 'Beplus Performance Booster Settings', 'beplus-performance-booster' ); ?></h2>
				</div>
				<div class="bepluspb-card-body bepluspb-status-table">
					<?php
					$row( __( 'Plugin Version', 'beplus-performance-booster' ), BEPLUSPB_VERSION, $badge( 'info', $t_info ) );
					$row( __( 'Plugin Directory', 'beplus-performance-booster' ), BEPLUSPB_PLUGIN_DIR );
					$row( __( 'Cache Directory', 'beplus-performance-booster' ), BEPLUSPB_CACHE_DIR );
					$row( __( 'Cache URL', 'beplus-performance-booster' ), $cache_url );
					$row( __( 'Options Key', 'beplus-performance-booster' ), BEPLUSPB_OPTIONS_KEY );
					$row( __( 'Master Cache Toggle', 'beplus-performance-booster' ), ! empty( $opts['cache_enabled'] ) ? $t_on : $t_off, $on_off( ! empty( $opts['cache_enabled'] ) ) );
					$row( __( 'CSS Minification', 'beplus-performance-booster' ), ! empty( $opts['minify_css_files'] ) ? $t_on : $t_off, $on_off( ! empty( $opts['minify_css_files'] ) ) );
					$row( __( 'JS Minification', 'beplus-performance-booster' ), ! empty( $opts['minify_js_files'] ) ? $t_on : $t_off, $on_off( ! empty( $opts['minify_js_files'] ) ) );
					$row( __( 'Lazy Load', 'beplus-performance-booster' ), ! empty( $opts['lazy_load'] ) ? $t_on : $t_off, $on_off( ! empty( $opts['lazy_load'] ) ) );
					$row( __( 'JS Defer', 'beplus-performance-booster' ), ! empty( $opts['js_defer'] ) ? $t_on : $t_off, $on_off( ! empty( $opts['js_defer'] ) ) );
					$delay_mode_label = ! empty( $opts['js_delay'] )
						? ( isset( $opts['js_delay_mode'] ) && 'advanced' === $opts['js_delay_mode'] ? __( 'Advanced', 'beplus-performance-booster' ) : __( 'Simple', 'beplus-performance-booster' ) )
						: $t_off;
					$row( __( 'JS Delay Mode', 'beplus-performance-booster' ), $delay_mode_label, $badge( ! empty( $opts['js_delay'] ) ? 'ok' : 'error', ! empty( $opts['js_delay'] ) ? $t_on : $t_off ) );
					if ( ! empty( $opts['js_delay'] ) && isset( $opts['js_delay_mode'] ) && 'advanced' === $opts['js_delay_mode'] ) {
						$rdelay = isset( $opts['js_delay_rdelay'] ) ? (int) $opts['js_delay_rdelay'] : 0;
						/* translators: %d: millisecond delay value. */
						$rdelay_label = 0 === $rdelay
							/* translators: %d: millisecond delay value. */
							? sprintf( __( '%d ms (wait for DOMContentLoaded)', 'beplus-performance-booster' ), $rdelay )
							/* translators: %d: millisecond delay value. */
							: sprintf( __( '%d ms', 'beplus-performance-booster' ), $rdelay );
						$row( __( 'JS Delay rdelay', 'beplus-performance-booster' ), $rdelay_label );
					}
					?>
				</div>
			</div>

			<?php // ---- Panel: PHP Extensions ------------------------------------- ?>
			<div class="bepluspb-card">
				<div class="bepluspb-card-header">
					<h2><?php esc_html_e( 'PHP Extensions', 'beplus-performance-booster' ); ?></h2>
				</div>
				<div class="bepluspb-card-body bepluspb-status-table">
					<?php
					foreach ( $ext_checks as $ext ) {
						$loaded = $ext['loaded'];
						if ( $loaded ) {
							$status_badge = $badge( 'ok', $t_ok );
						} elseif ( $ext['required'] ) {
							$status_badge = $badge( 'error', $t_error );
						} else {
							$status_badge = $badge( 'warn', $t_missing );
						}
						$row( esc_html( $ext['label'] ), esc_html( $ext['note'] ), $status_badge );
					}
					?>
				</div>
			</div>

		</div><!-- .bepluspb-status-grid -->
		<?php
	}

	/**
	 * Render the Recommendations panel shown at the top of the Status tab.
	 *
	 * Builds a list of:
	 *  - ❌ Errors   — block correct operation (e.g. cache dir not writable).
	 *  - ⚠️ Warnings — sub-optimal config (e.g. WP_DEBUG on, old PHP, multisite).
	 *  - 💡 Suggestions — recommended features not yet enabled (lazy load, defer JS…).
	 *  - ✅ Good     — shown only when everything looks healthy.
	 *
	 * Each item has a one-line "what" + "why/how" message and, when relevant,
	 * a link that jumps to the right tab so the user can act immediately.
	 *
	 * @param array  $opts            Current option values.
	 * @param bool   $dir_writable    Whether the cache directory (or its parent) is writable.
	 * @param bool   $dir_exists      Whether the cache directory exists.
	 * @param bool   $ht_writable     Whether the .htaccess file (or its parent) is writable.
	 * @param bool   $ht_exists       Whether the .htaccess file exists.
	 * @param bool   $wc_writable     Whether wp-content is writable.
	 * @param string $php_ver        Current PHP version string.
	 * @param string $wp_ver         Current WordPress version string.
	 * @param bool   $wp_debug        Whether WP_DEBUG is on.
	 * @param bool   $is_multi        Whether this is a multisite install.
	 * @param bool   $has_zlib        Whether the Zlib PHP extension is loaded.
	 * @param int    $mem_bytes       PHP memory limit in bytes (-1 = unlimited).
	 * @param array  $flagged_plugins Detected potentially-conflicting active plugins.
	 */
	private static function render_status_recommendations(
		$opts,
		$dir_writable,
		$dir_exists,
		$ht_writable,
		$ht_exists,
		$wc_writable,
		$php_ver,
		$wp_ver,
		$wp_debug,
		$is_multi,
		$has_zlib,
		$mem_bytes,
		$flagged_plugins
	) {
		$settings_url = admin_url( 'options-general.php?page=beplus-performance-booster' );
		$tab_link     = static function ( $tab, $label ) use ( $settings_url ) {
			return '<a href="' . esc_url( $settings_url . '#bepluspb-tab-' . $tab ) . '" class="bepluspb-rec-link">' . esc_html( $label ) . ' →</a>';
		};

		$errors      = array();
		$warnings    = array();
		$suggestions = array();

		// =====================================================================
		// Errors — things that break or block the plugin
		// =====================================================================

		if ( ! $wc_writable ) {
			$errors[] = array(
				'title'  => __( 'wp-content is not writable', 'beplus-performance-booster' ),
				'detail' => __( 'The plugin cannot create the cache directory inside wp-content. Set wp-content permissions to 755 (or contact your host).', 'beplus-performance-booster' ),
			);
		}

		if ( ! $dir_writable ) {
			$errors[] = array(
				'title'  => __( 'Cache directory is not writable', 'beplus-performance-booster' ),
				'detail' => sprintf(
					/* translators: %s: cache directory path */
					__( 'Minified CSS/JS files cannot be written to %s. The plugin will silently fall back to the original (un-minified) files. Set the directory to 755.', 'beplus-performance-booster' ),
					'<code>' . esc_html( BEPLUSPB_CACHE_DIR ) . '</code>'
				),
			);
		}

		if ( ! empty( $opts['cache_headers'] ) && ! $ht_writable ) {
			$errors[] = array(
				'title'  => __( 'Browser caching is on but .htaccess is not writable', 'beplus-performance-booster' ),
				'detail' => __( 'The browser cache rules cannot be injected into .htaccess. Make the .htaccess file writable (644) and re-save the Cache Exclusions tab.', 'beplus-performance-booster' ),
				'action' => $tab_link( 'advanced', __( 'Open Cache Exclusions', 'beplus-performance-booster' ) ),
			);
		}

		// =====================================================================
		// Warnings — sub-optimal but not breaking
		// =====================================================================

		if ( empty( $opts['cache_enabled'] ) ) {
			$warnings[] = array(
				'title'  => __( 'Master cache is OFF', 'beplus-performance-booster' ),
				'detail' => __( 'All CSS/JS minification, caching, lazy loading, and cleanup features are currently disabled. Turn on the master toggle on the Dashboard to start optimising.', 'beplus-performance-booster' ),
				'action' => $tab_link( 'dashboard', __( 'Open Dashboard', 'beplus-performance-booster' ) ),
			);
		}

		if ( version_compare( $php_ver, '7.4', '<' ) ) {
			$warnings[] = array(
				'title'  => sprintf(
					/* translators: %s: detected PHP version */
					__( 'PHP %s is outdated', 'beplus-performance-booster' ),
					esc_html( $php_ver )
				),
				'detail' => __( 'WordPress recommends PHP 7.4 or newer (8.1+ for best performance). Ask your host to upgrade.', 'beplus-performance-booster' ),
			);
		}

		if ( -1 !== $mem_bytes && $mem_bytes < 128 * 1024 * 1024 ) {
			$warnings[] = array(
				'title'  => __( 'PHP memory_limit is low', 'beplus-performance-booster' ),
				'detail' => __( 'Minifying many large CSS/JS files can hit the PHP memory limit. Set memory_limit to at least 128M in php.ini or wp-config.php.', 'beplus-performance-booster' ),
			);
		}

		if ( $wp_debug ) {
			$warnings[] = array(
				'title'  => __( 'WP_DEBUG is on', 'beplus-performance-booster' ),
				'detail' => __( 'WP_DEBUG should be OFF on production sites. Set WP_DEBUG to false in wp-config.php to avoid surfacing PHP notices to visitors.', 'beplus-performance-booster' ),
			);
		}

		if ( $is_multi ) {
			$warnings[] = array(
				'title'  => __( 'WordPress Multisite detected', 'beplus-performance-booster' ),
				'detail' => __( 'This plugin is not designed for Multisite. The cache directory and .htaccess block are shared across all sub-sites. Install it on individual sub-sites instead of network-activating.', 'beplus-performance-booster' ),
			);
		}

		if ( ! $has_zlib ) {
			$warnings[] = array(
				'title'  => __( 'Zlib extension missing', 'beplus-performance-booster' ),
				'detail' => __( 'PHP Zlib is not loaded, so gzip compression cannot be applied at the PHP level. Ask your host to enable the zlib extension.', 'beplus-performance-booster' ),
			);
		}

		if ( ! empty( $flagged_plugins ) ) {
			$names = array();
			foreach ( $flagged_plugins as $data ) {
				$names[] = $data['Name'];
			}
			$warnings[] = array(
				'title'  => __( 'Another caching/minification plugin is active', 'beplus-performance-booster' ),
				'detail' => sprintf(
					/* translators: %s: comma-separated list of plugin names */
					__( 'Running two optimisation plugins can produce double-minified or broken assets. Detected: %s. Deactivate one of them to be safe.', 'beplus-performance-booster' ),
					'<em>' . esc_html( implode( ', ', $names ) ) . '</em>'
				),
			);
		}

		// =====================================================================
		// Suggestions — recommended features not yet enabled
		// =====================================================================

		// Only suggest enabling features when the master cache is ON; otherwise the
		// "Master cache is OFF" warning above is the priority action.
		if ( ! empty( $opts['cache_enabled'] ) ) {

			if ( empty( $opts['lazy_load'] ) ) {
				$suggestions[] = array(
					'title'  => __( 'Enable lazy loading', 'beplus-performance-booster' ),
					'detail' => __( 'Add loading="lazy" to off-screen images so they only load when scrolled into view — large Core Web Vitals win on image-heavy pages.', 'beplus-performance-booster' ),
					'action' => $tab_link( 'cache_files', __( 'Open Cache Files tab', 'beplus-performance-booster' ) ),
				);
			}

			if ( empty( $opts['minify_css_files'] ) && $dir_writable ) {
				$suggestions[] = array(
					'title'  => __( 'Minify CSS files', 'beplus-performance-booster' ),
					'detail' => __( 'Strip comments and whitespace from every enqueued CSS file and serve the cached version. Typically cuts CSS payload 10–30%.', 'beplus-performance-booster' ),
					'action' => $tab_link( 'cache_files', __( 'Open Cache Files tab', 'beplus-performance-booster' ) ),
				);
			}

			if ( empty( $opts['minify_js_files'] ) && $dir_writable ) {
				$suggestions[] = array(
					'title'  => __( 'Minify JS files', 'beplus-performance-booster' ),
					'detail' => __( 'Strip comments and whitespace from every enqueued JS file. Saves bytes and improves time-to-interactive.', 'beplus-performance-booster' ),
					'action' => $tab_link( 'cache_files', __( 'Open Cache Files tab', 'beplus-performance-booster' ) ),
				);
			}

			if ( empty( $opts['js_defer'] ) ) {
				$suggestions[] = array(
					'title'  => __( 'Defer non-critical JS', 'beplus-performance-booster' ),
					'detail' => __( 'Add the defer attribute to scripts so they fetch in parallel and execute after HTML parsing — major boost to First Contentful Paint.', 'beplus-performance-booster' ),
					'action' => $tab_link( 'cache_files', __( 'Open Cache Files tab', 'beplus-performance-booster' ) ),
				);
			}

			if ( empty( $opts['remove_emoji'] ) ) {
				$suggestions[] = array(
					'title'  => __( 'Remove emoji scripts', 'beplus-performance-booster' ),
					'detail' => __( 'WordPress loads a JS+CSS pair to polyfill emoji on old browsers that no longer exist. Removing it shaves ~10KB and one HTTP request from every page.', 'beplus-performance-booster' ),
					'action' => $tab_link( 'cleanup', __( 'Open Cleanup tab', 'beplus-performance-booster' ) ),
				);
			}

			if ( empty( $opts['cache_headers'] ) && $ht_writable ) {
				$suggestions[] = array(
					'title'  => __( 'Enable browser cache headers', 'beplus-performance-booster' ),
					'detail' => __( 'Inject 1-year cache headers and gzip/brotli rules into .htaccess so returning visitors load static assets from their local cache.', 'beplus-performance-booster' ),
					'action' => $tab_link( 'advanced', __( 'Open Cache Exclusions tab', 'beplus-performance-booster' ) ),
				);
			}

			if ( empty( $opts['html_minify'] ) ) {
				$suggestions[] = array(
					'title'  => __( 'Minify HTML output', 'beplus-performance-booster' ),
					'detail' => __( 'Collapse whitespace between HTML tags in the rendered page. Small per-request win that adds up across the whole site.', 'beplus-performance-booster' ),
					'action' => $tab_link( 'cleanup', __( 'Open Cleanup tab', 'beplus-performance-booster' ) ),
				);
			}
		}

		$total = count( $errors ) + count( $warnings ) + count( $suggestions );

		// ---- Render -------------------------------------------------------------
		?>
		<div class="bepluspb-card bepluspb-recommend-card">
			<div class="bepluspb-card-header">
				<h2>
					<?php esc_html_e( 'Recommendations', 'beplus-performance-booster' ); ?>
					<?php if ( $total > 0 ) : ?>
						<span class="bepluspb-rec-count"><?php echo esc_html( (string) $total ); ?></span>
					<?php endif; ?>
				</h2>
				<p>
					<?php esc_html_e( 'Targeted fixes and improvements to keep caching healthy and your site fast.', 'beplus-performance-booster' ); ?>
				</p>
			</div>
			<div class="bepluspb-card-body">

				<?php if ( 0 === $total ) : ?>
					<div class="bepluspb-rec-item bepluspb-rec-item--ok">
						<span class="bepluspb-rec-icon" aria-hidden="true">✅</span>
						<div class="bepluspb-rec-text">
							<strong><?php esc_html_e( 'Everything looks good', 'beplus-performance-booster' ); ?></strong>
							<p><?php esc_html_e( 'No errors, warnings, or pending recommendations were detected on this site.', 'beplus-performance-booster' ); ?></p>
						</div>
					</div>
				<?php else : ?>

					<?php foreach ( $errors as $item ) : ?>
					<div class="bepluspb-rec-item bepluspb-rec-item--error">
						<span class="bepluspb-rec-icon" aria-hidden="true">⛔</span>
						<div class="bepluspb-rec-text">
							<strong><?php echo esc_html( $item['title'] ); ?></strong>
							<p>
								<?php
								// $detail may contain pre-escaped HTML (e.g. <code>, <em>) built above.
								echo wp_kses(
									$item['detail'],
									array(
										'code'   => array(),
										'em'     => array(),
										'strong' => array(),
									)
								);
								?>
							</p>
							<?php if ( ! empty( $item['action'] ) ) : ?>
								<?php
								echo wp_kses(
									$item['action'],
									array(
										'a' => array(
											'href'  => array(),
											'class' => array(),
										),
									)
								);
								?>
							<?php endif; ?>
						</div>
					</div>
					<?php endforeach; ?>

					<?php foreach ( $warnings as $item ) : ?>
					<div class="bepluspb-rec-item bepluspb-rec-item--warn">
						<span class="bepluspb-rec-icon" aria-hidden="true">⚠️</span>
						<div class="bepluspb-rec-text">
							<strong><?php echo esc_html( $item['title'] ); ?></strong>
							<p>
								<?php
								echo wp_kses(
									$item['detail'],
									array(
										'code'   => array(),
										'em'     => array(),
										'strong' => array(),
									)
								);
								?>
							</p>
							<?php if ( ! empty( $item['action'] ) ) : ?>
								<?php
								echo wp_kses(
									$item['action'],
									array(
										'a' => array(
											'href'  => array(),
											'class' => array(),
										),
									)
								);
								?>
							<?php endif; ?>
						</div>
					</div>
					<?php endforeach; ?>

					<?php foreach ( $suggestions as $item ) : ?>
					<div class="bepluspb-rec-item bepluspb-rec-item--tip">
						<span class="bepluspb-rec-icon" aria-hidden="true">💡</span>
						<div class="bepluspb-rec-text">
							<strong><?php echo esc_html( $item['title'] ); ?></strong>
							<p><?php echo esc_html( $item['detail'] ); ?></p>
							<?php if ( ! empty( $item['action'] ) ) : ?>
								<?php
								echo wp_kses(
									$item['action'],
									array(
										'a' => array(
											'href'  => array(),
											'class' => array(),
										),
									)
								);
								?>
							<?php endif; ?>
						</div>
					</div>
					<?php endforeach; ?>

				<?php endif; ?>

			</div>
		</div>
		<?php
	}
}
